
#pragma config(Sensor, dgtl1,  shooter,        sensorDigitalOut)
#pragma config(Motor,  port2,           LF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LM,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RF,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RB,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int LiftPow=0;
task main()
{
	while (1)
	{
		if((vexRT[Ch3]-vexRT[Ch4])>15)//forwards
		{
			motor[LM]=120;
			motor[LF]=-22+(vexRT[Ch3]-vexRT[Ch4])*1.14;
			motor[LB]=-22+(vexRT[Ch3]-vexRT[Ch4])*1.14;

		}
		else if((vexRT[Ch3]-vexRT[Ch4])<-15)//backwards
		{
			motor[LM]=-120;
			motor[LF]=22+(vexRT[Ch3]-vexRT[Ch4])*1.14;
			motor[LB]=22+(vexRT[Ch3]-vexRT[Ch4])*1.14;

		}
		else
		{
			motor[LF]=0;
			motor[LM]=0;
			motor[LB]=0;

		}
		if((vexRT[Ch3]+vexRT[Ch4])>15)//forwards
		{
			motor[RM]=120;
			motor[RB]=-22+(vexRT[Ch3]+vexRT[Ch4])*1.14;
			motor[RF]=-22+(vexRT[Ch3]+vexRT[Ch4])*1.14;
		}
		else if((vexRT[Ch3]+vexRT[Ch4])<-15)//backwards
		{
			motor[RM]=-120;
			motor[RB]=22+(vexRT[Ch3]+vexRT[Ch4])*1.14;
			motor[RF]=22+(vexRT[Ch3]+vexRT[Ch4])*1.14;
		}
		else
		{
			motor[RF]=0;
			motor[RM]=0;
			motor[RB]=0;
		}
		if (abs(vexRT[Ch2])>10)
		{
			motor[port8]=-vexRT[Ch2];
			motor[port9]=-vexRT[Ch2];
		}

		else
		{

			motor[port8]=-10;
			motor[port9]=-10;


		}

		if (vexRT[Btn5U]==1)
		{motor[port1]=127;
		}
		else if (vexRT[Btn5D]==1)
		{motor[port1]=-127;
		}
		else {motor[port1]=10;}

		if (vexRT[Btn7U]==1)
		{motor[port10]=127;
		}
		else if (vexRT[Btn7D]==1)
		{motor[port10]=-127;
		}
		else {motor[port10]=0;}
if (vexRT[Btn6U]==1)
{SensorValue[shooter]=1;}
else {SensorValue[shooter]=0;}

	}
}
