#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  Load,           sensorTouch)
#pragma config(Sensor, I2C_1,  Release,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LoadBall,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Roller,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LM,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LY,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Flip,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RY,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ReleaseBall,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Feeder,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int LiftPow=0;
int shootball=0;
int R=4;
int FR=4;
task Shoot()
{	while(1)
{
	if (shootball==1)
	{while (abs(SensorValue(Release))<500){motor[ReleaseBall]=100;}
		motor[ReleaseBall]=0;
		wait1Msec(200);
		while (abs(SensorValue(Release))>100){motor[ReleaseBall]=-50;motor[LoadBall]=70;}

		motor[ReleaseBall]=0;
		clearTimer(T1);
		while((time1[T1]<2000)&&SensorValue[Load]==0){motor[LoadBall]=127;}
		motor[LoadBall]=0;
		shootball=0;
	}
	else {motor[ReleaseBall]=0;}
}
}

task main()
{startTask(Shoot);
	SensorValue[Release]=0;
	SensorValue[Load]=0;
	while (1)
	{
		if((vexRT[Ch3]-vexRT[Ch4])>15)//forwards
		{
			motor[LM]=120;
			motor[LY]=-100.0+(vexRT[Ch3]-vexRT[Ch4])*2.0;
		}
		else if((vexRT[Ch3]-vexRT[Ch4])<-15)//backwards
		{
			motor[LM]=-120;
			motor[LY]=100.0+(vexRT[Ch3]-vexRT[Ch4])*2.0;

		}
		else
		{
			motor[LM]=0;
			motor[LY]=0;


		}
		if((vexRT[Ch3]+vexRT[Ch4])>15)//forwards
		{
			motor[RM]=120;
			motor[RY]=-120.0+(vexRT[Ch3]+vexRT[Ch4])*2.0;
		}
		else if((vexRT[Ch3]+vexRT[Ch4])<-15)//backwards
		{
			motor[RM]=-120;
			motor[RY]=120.0+(vexRT[Ch3]+vexRT[Ch4])*2.0;
		}
		else
		{
			motor[RM]=0;
			motor[RY]=0;
		}
		/*		if (abs(vexRT[Ch2])>10)
		{
		motor[port8]=-vexRT[Ch2];
		motor[port9]=-vexRT[Ch2];
		}

		else
		{

		motor[port8]=-10;
		motor[port9]=-10;


		}*/

		if (vexRT[Btn5U]==1)
		{motor[Flip]=127;
		}
		else if (vexRT[Btn5D]==1)
		{motor[Flip]=-127;
		}
		else {motor[Flip]=10;}

		if (vexRT[Btn8D]==1)
		{shootball=1;
		}
		else {}
		if (abs(vexRT[Ch2])>15){motor[Lift]=vexRT[Ch2];}
		else{motor[Lift]=10;}


		if(FR == 4 && vexRT[Btn8R] == 0){ motor[Feeder] = 0;motor[Roller] =0; FR = 1;} //Roller
else if(FR == 1 && vexRT[Btn8R] == 1){ motor[Feeder] = 120;FR = 2;R=4;}
else if(FR == 2 && vexRT[Btn8R] == 0){ motor[Feeder] = 120; FR = 3;R=4;}
else if(FR == 3 && vexRT[Btn8R] == 1){ motor[Feeder] = 0; motor[Roller] =0;FR = 4;}
else{}
						if(R == 4 && (FR == 4||FR == 3)&&vexRT[Btn8U] == 0){ motor[Roller] = -120; R = 1;} //Roller
else if(R == 1 && (FR == 4||FR == 3)&&vexRT[Btn8U] == 1){ motor[Roller] = 120; R = 2;}
else if(R == 2 && (FR == 4||FR == 3)&&vexRT[Btn8U] == 0){ motor[Roller] = 120; R = 3;}
else if(R == 3 && (FR == 4||FR == 3)&&vexRT[Btn8U] == 1){ motor[Roller] = -120; R = 4;}
		else{}
	}
}
