#pragma config(Motor,  port2,           LF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LM,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RF,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RB,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int LiftPow=0;
task main()
{
	while (1)
	{
		if((vexRT[Ch3]-vexRT[Ch4])>15)//forwards
		{
			motor[LM]=120;
			motor[LF]=-120+(vexRT[Ch3]-vexRT[Ch4])*2;
			motor[LB]=-120+(vexRT[Ch3]-vexRT[Ch4])*2;

		}
		else if((vexRT[Ch3]-vexRT[Ch4])<-15)//backwards
		{
			motor[LM]=-120;
			motor[LF]=120+(vexRT[Ch3]-vexRT[Ch4])*2;
			motor[LB]=120+(vexRT[Ch3]-vexRT[Ch4])*2;

		}
		else
		{
			motor[LF]=0;
			motor[LM]=0;
			motor[LB]=0;

		}
		if((vexRT[Ch3]+vexRT[Ch4])>15)//forwards
		{
			motor[RM]=120;
			motor[RB]=-120+(vexRT[Ch3]+vexRT[Ch4])*2;
			motor[RF]=-120+(vexRT[Ch3]+vexRT[Ch4])*2;
		}
		else if((vexRT[Ch3]+vexRT[Ch4])<-15)//backwards
		{
			motor[RM]=-120;
			motor[RB]=120+(vexRT[Ch3]+vexRT[Ch4])*2;
			motor[RF]=120+(vexRT[Ch3]+vexRT[Ch4])*2;
		}
		else
		{
			motor[RF]=0;
			motor[RM]=0;
			motor[RB]=0;
		}
		if (abs(vexRT[Ch2])>10)
		{
			motor[port8]=-vexRT[Ch2];
			motor[port9]=-vexRT[Ch2];
		}

		else
		{

			motor[port8]=-10;
			motor[port9]=-10;


		}

		if (vexRT[Btn5U]==1)
		{motor[port1]=127;
		}
		else if (vexRT[Btn5D]==1)
		{motor[port1]=-127;
		}
		else {motor[port1]=10;}

	}
}
