#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  Load,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  Release,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           LF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LM,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RF,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RB,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ReleaseBall,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LoadBall,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int LiftPow=0;
int shootball=0;
task Shoot()
{	while(1)
{
	if (shootball==1)
	{while (SensorValue(Release)<500){motor[ReleaseBall]=100;}
		motor[ReleaseBall]=0;
		wait1Msec(400);
		while (SensorValue(Release)>200){motor[ReleaseBall]=-70;motor[LoadBall]=100;}
		motor[ReleaseBall]=0;
		SensorValue[Load]=0;
		clearTimer(T1);
		while((time1[T1]<1500)&& abs(SensorValue[Load])<690){motor[LoadBall]=127;}
		motor[LoadBall]=0;
		shootball=0;
	}
	else {motor[ReleaseBall]=0;}
}
}

task main()
{startTask(Shoot);
	SensorValue[Release]=0;
	SensorValue[Load]=0;
	while (1)
	{
		if((vexRT[Ch3]-vexRT[Ch4])>15)//forwards
		{
			motor[LM]=120;
			motor[LF]=-22+(vexRT[Ch3]-vexRT[Ch4])*1.14;
			motor[LB]=-22+(vexRT[Ch3]-vexRT[Ch4])*1.14;

		}
		else if((vexRT[Ch3]-vexRT[Ch4])<-15)//backwards
		{
			motor[LM]=-120;
			motor[LF]=22+(vexRT[Ch3]-vexRT[Ch4])*1.14;
			motor[LB]=22+(vexRT[Ch3]-vexRT[Ch4])*1.14;

		}
		else
		{
			motor[LF]=0;
			motor[LM]=0;
			motor[LB]=0;

		}
		if((vexRT[Ch3]+vexRT[Ch4])>15)//forwards
		{
			motor[RM]=120;
			motor[RB]=-22+(vexRT[Ch3]+vexRT[Ch4])*1.14;
			motor[RF]=-22+(vexRT[Ch3]+vexRT[Ch4])*1.14;
		}
		else if((vexRT[Ch3]+vexRT[Ch4])<-15)//backwards
		{
			motor[RM]=-120;
			motor[RB]=22+(vexRT[Ch3]+vexRT[Ch4])*1.14;
			motor[RF]=22+(vexRT[Ch3]+vexRT[Ch4])*1.14;
		}
		else
		{
			motor[RF]=0;
			motor[RM]=0;
			motor[RB]=0;
		}
		/*		if (abs(vexRT[Ch2])>10)
		{
		motor[port8]=-vexRT[Ch2];
		motor[port9]=-vexRT[Ch2];
		}

		else
		{

		motor[port8]=-10;
		motor[port9]=-10;


		}*/

		if (vexRT[Btn5U]==1)
		{motor[port1]=127;
		}
		else if (vexRT[Btn5D]==1)
		{motor[port1]=-127;
		}
		else {motor[port1]=10;}

		if (vexRT[Btn7U]==1)
		{shootball=1;
		}
		else {}
	}
}
