#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    IRLift,         sensorAnalog)
#pragma config(Sensor, in3,    IRFB,           sensorAnalog)
#pragma config(Sensor, in4,    RLine,          sensorLineFollower)
#pragma config(Sensor, in5,    LLine,          sensorLineFollower)
#pragma config(Sensor, in6,    MPot,           sensorPotentiometer)
#pragma config(Sensor, in7,    BackUpBattery,  sensorAnalog)
#pragma config(Sensor, dgtl11, LiftLimit,      sensorTouch)
#pragma config(Sensor, dgtl12, FourBarLimit,   sensorTouch)
#pragma config(Sensor, I2C_1,  LEnc,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  REnc,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  LiEnc,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  FBEnc,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  rol,            sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           MG,            tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           R1,            tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           RM,            tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           fb1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LiftR,         tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port6,           LiftL,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           L1,            tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port8,           LM,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           fb2,           tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port10,          roller,        tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEBUG 0

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//GLOBAL VARIABLES//
int alliance = 4;
int autonomousN = 5;
int stage = 1;
int MoveCounter = 0;
float bs1 = 1, bs2 = 1;//8.0/nImmediateBatteryLevel/1000.0;
int gyroVal = SensorValue[gyro];
int fbStatus = 1;	//ACTUATE FB
int fbAv = 0;//LET PROGROMER KNOW ABOUT THE AVAILABILITY OF FB

float avgSpeed = 0;
float avgError = 0;
//DEBUG VARS
int encVal = 0;
int state = 0;

///////////////////////////BEGIN INCLUDED FILES
//#include "Vex_Competition_Includes.c"
#include "vex.c"
#include "BasicMove.c"
#include "Tasks.c"
#include "anglePID.c"
#include "DebugCode.c"
#include "BlueAuto1.c"
#include "BlueAuto2.c"
#include "BlueAuto3.c";
#include "BlueAuto4.c";
#include "RedAuto1.c"
#include "RedAuto2.c"
#include "RedAuto3.c"

void pre_auton()
{
	#include "PreAuto.c"
	bStopTasksBetweenModes = false;
}

task autonomous()
{
	stopTask(usercontrol);
	//NEW: ACCOUNT FOR BATTERY VOLTAGE DIFFERANCE DURING AUTONOMOUS
	//FOUR BAR CONTROL GIVEN TO AUTO ROUTINE
	fbStatus = -1;
	startTask(FourBar);
	//////////////////////////////////////////////
	#include "Auto.c"
}

task usercontrol()
{
	stopTask(autonomous);
	#include "Driver.c"
}
