#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl4,  Sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl7,  Blue,           sensorDigitalOut)
#pragma config(Sensor, dgtl10, White,          sensorDigitalOut)
#pragma config(Sensor, dgtl11, IRMid,          sensorDigitalIn)
#pragma config(Sensor, dgtl12, IRTop,          sensorDigitalIn)
#pragma config(Sensor, I2C_1,  Load,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Lift1,         tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           Roller,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LM,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LY,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Flip,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RY,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           punch,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Feeder,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Lift2,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int LiftPow=0;
int shootball=0;
int R=4;
int FR=4;
float ddir=1.0;
float BallTime=0;
float Dy=0;
int rollbackcounter=0;

/*void ScoreCap()
{while(SensorValue[IRMid]==1)
{
while (SensorValue[IRMid]==1&&(SensorValue[IRLeft]==0||SensorValue[IRRight]==0))
{if (SensorValue[IRLeft]==0){
motor[LM] = -50;
motor[LY] = -50;
motor[RM]=50;
motor[RY]=50;}
else	if (SensorValue[IRRight]==0){
motor[LM] = 50;
motor[LY] = 50;
motor[RM]=-50;
motor[RY]=-50;}
}
motor[LM] = 50;
motor[LY] = 50;

motor[RM]=50;
motor[RY]=50;
wait1Msec(10);
}
motor[LM] = 0;
motor[LY] = 0;

motor[RM]=0;
motor[RY]=0;
}*/
task RollBack()
{while(1)
	{if (SensorValue[IRTop]==0)
		{rollbackcounter=1;
			wait1Msec(300);
			rollbackcounter=0;
			FR=2;
			while (SensorValue[IRTop]==0){}
		}
		else{}
	}
}
task HeightCalc()
{
	while(1)
	{BallTime=SensorValue[Sonar]/185.41;
		Dy=186.0*BallTime-(0.5*386.08*BallTime*BallTime);
		if (Dy>26&&Dy<32){SensorValue[White]=0;SensorValue[Blue]=1;}
		else if(Dy>40&&Dy<46){SensorValue[White]=1;SensorValue[Blue]=0;}
		else {SensorValue[White]=1;SensorValue[Blue]=1;}
		wait1Msec(100);
	}
}

task Shoot()
{
	while(1)
	{
		if (shootball==1)
		{
			{while (abs(SensorValue(Load))<627.2){motor[punch]=127;}
				SensorValue(Load)=0;
				motor[punch]=-50;
				wait1Msec(75);


				shootball=0;

			}

		}
		else {motor[punch]=0;}
	}
}

task main()
{SensorValue(Load)=0;
	startTask(Shoot);
	startTask(HeightCalc);
	startTask(RollBack);
	SensorValue[Load]=0;
	while (1)
	{

		if(abs(vexRT[Ch3])>15 ||abs(vexRT[Ch4])>15)//backwards
		{
			motor[LM] = (ddir*vexRT[Ch3] + vexRT[Ch4]/2);
			motor[LY] = (ddir*vexRT[Ch3] + vexRT[Ch4]/2);


			motor[RM] = (ddir*vexRT[Ch3] - vexRT[Ch4]/2);
			motor[RY] = (ddir*vexRT[Ch3] - vexRT[Ch4]/2);
		}
		else
		{
			motor[LM] = 0;
			motor[LY] = 0;

			motor[RM]=0;
			motor[RY]=0;
		}


		/*		if (abs(vexRT[Ch2])>10)
		{
		motor[port8]=-vexRT[Ch2];
		motor[port9]=-vexRT[Ch2];
		}

		else
		{
		motor[port8]=-10;
		motor[port9]=-10;
		}*/

		if (vexRT[Btn6U]==1){motor[Flip]=127;}
		else if (vexRT[Btn6D]==1){motor[Flip]=-127;}
		else if(motor[Flip]==127||motor[Flip]==20){motor[Flip]=20;}
		else {motor[Flip]=8;}

		if (vexRT[Btn8D]==1&&SensorValue[IRTop]==0){shootball=1;}
		else {}

		if (abs(vexRT[Ch2])>15){motor[Lift1]=vexRT[Ch2]; motor[Lift2]=vexRT[Ch2];}
		else{motor[Lift1]=15; motor[Lift2]=15;}


		if (SensorValue[IRTop]==0&&SensorValue[IRMid]==0){FR = 4;R=4;}
		else{}
		if (vexRT[Btn8L]==1){motor[Feeder] =-80;}
		else if (motor[Feeder] ==-80){FR=4;}
		else{}
		if (rollbackcounter==1){ motor[Feeder] = -90;}
		else if(FR == 4 && vexRT[Btn8R] == 0){ motor[Feeder] = 0;motor[Roller] =0; FR = 1;} //Roller
		else if(FR == 1 && vexRT[Btn8R] == 1){ motor[Feeder] = 120;FR = 2;R=4;}
		else if(FR == 2 && vexRT[Btn8R] == 0){ motor[Feeder] = 120; FR = 3;R=4;}
		else if(FR == 3 && vexRT[Btn8R] == 1){ motor[Feeder] = 0; motor[Roller] =0;FR = 4;}
		else{}
		if(R == 4 && (FR == 4||FR == 3)&&vexRT[Btn8U] == 0){ motor[Roller] = -120; R = 1;} //Roller
		else if(R == 1 && (FR == 4||FR == 3)&&vexRT[Btn8U] == 1){ motor[Roller] = 120; R = 2;}
		else if(R == 2 && (FR == 4||FR == 3)&&vexRT[Btn8U] == 0){ motor[Roller] = 120; R = 3;}
		else if(R == 3 && (FR == 4||FR == 3)&&vexRT[Btn8U] == 1){ motor[Roller] = -120; R = 4;}
		else{}

		if(ddir==1.01 && vexRT[Btn5D] == 0){ ddir = 1.0;} //Roller
		else if(ddir== 1.0 &&vexRT[Btn5D] == 1){ ddir = -1.01;}
		else if(ddir == -1.01 && vexRT[Btn5D] == 0){ ddir= -1.0;}
		else if(ddir == -1.0 && vexRT[Btn5D] == 1){ddir= 1.01;}
		else{}
		/*if (vexRT[Btn7U]==1){ScoreCap();}
		else{}*/
	}
}
